[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Board settings for 16MB Flash and 8MB OPI PSRAM (N16R8)
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -I src/ui
    -I src/images

lib_deps =
    moononournation/GFX Library for Arduino @ 1.6.0
    lvgl/lvgl @ 8.3.11
